import SwiftUI
import UIKit

@MainActor
struct LearningsPDFRenderer {

    static func render(book: Book, accentColor: Color, learnings: [Learning]) -> URL? {
        let pageSize = CGSize(width: 612, height: 792) // US Letter at 72 dpi
        let margin: CGFloat = 56
        let contentWidth = pageSize.width - margin * 2

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: pageSize))

        let tempURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(book.title) — Distill Learnings.pdf")

        do {
            try renderer.writePDF(to: tempURL) { ctx in
                var yOffset: CGFloat = margin
                var currentPage = 0

                func beginPage() {
                    ctx.beginPage()
                    currentPage += 1
                    yOffset = margin
                    drawHeader()
                }

                func drawHeader() {
                    let titleAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 22, weight: .bold),
                        .foregroundColor: UIColor.label
                    ]
                    let authorAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 13, weight: .regular),
                        .foregroundColor: UIColor.secondaryLabel
                    ]
                    let badgeAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 11, weight: .medium),
                        .foregroundColor: UIColor.secondaryLabel
                    ]

                    let titleStr = NSAttributedString(string: book.title, attributes: titleAttrs)
                    let titleSize = titleStr.boundingRect(with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                                                          options: .usesLineFragmentOrigin, context: nil).size
                    titleStr.draw(in: CGRect(x: margin, y: yOffset, width: contentWidth, height: titleSize.height))
                    yOffset += titleSize.height + 4

                    let authorStr = NSAttributedString(string: book.author, attributes: authorAttrs)
                    authorStr.draw(at: CGPoint(x: margin, y: yOffset))
                    yOffset += 20

                    let badge = NSAttributedString(string: "\(learnings.count) core learnings · Generated by Distill", attributes: badgeAttrs)
                    badge.draw(at: CGPoint(x: margin, y: yOffset))
                    yOffset += 24

                    let dividerRect = CGRect(x: margin, y: yOffset, width: contentWidth, height: 0.5)
                    UIColor.separator.setFill()
                    UIRectFill(dividerRect)
                    yOffset += 16
                }

                func drawLearning(_ learning: Learning) {
                    let chapterAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 9, weight: .semibold),
                        .foregroundColor: UIColor(accentColor)
                    ]
                    let textAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 12, weight: .regular),
                        .foregroundColor: UIColor.label,
                        .paragraphStyle: {
                            let ps = NSMutableParagraphStyle()
                            ps.lineSpacing = 3
                            return ps
                        }()
                    ]

                    var blockHeight: CGFloat = 0
                    var chapterHeight: CGFloat = 0

                    if !learning.chapter.isEmpty {
                        let chapterStr = NSAttributedString(string: learning.chapter.uppercased(), attributes: chapterAttrs)
                        chapterHeight = chapterStr.boundingRect(with: CGSize(width: contentWidth - 16, height: .greatestFiniteMagnitude),
                                                                options: .usesLineFragmentOrigin, context: nil).size.height + 4
                        blockHeight += chapterHeight
                    }

                    let textStr = NSAttributedString(string: learning.text, attributes: textAttrs)
                    let textHeight = textStr.boundingRect(with: CGSize(width: contentWidth - 16, height: .greatestFiniteMagnitude),
                                                          options: .usesLineFragmentOrigin, context: nil).size.height
                    blockHeight += textHeight + 24 // padding

                    if yOffset + blockHeight > pageSize.height - margin {
                        beginPage()
                    }

                    let boxRect = CGRect(x: margin, y: yOffset, width: contentWidth, height: blockHeight)
                    let path = UIBezierPath(roundedRect: boxRect, cornerRadius: 8)
                    UIColor.systemGray6.setFill()
                    path.fill()

                    var innerY = yOffset + 12
                    if !learning.chapter.isEmpty {
                        let chapterStr = NSAttributedString(string: learning.chapter.uppercased(), attributes: chapterAttrs)
                        chapterStr.draw(in: CGRect(x: margin + 12, y: innerY, width: contentWidth - 24, height: chapterHeight))
                        innerY += chapterHeight
                    }

                    textStr.draw(in: CGRect(x: margin + 12, y: innerY, width: contentWidth - 24, height: textHeight + 4))
                    yOffset += blockHeight + 10
                }

                beginPage()
                for learning in learnings {
                    drawLearning(learning)
                }

                let footerAttrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.systemFont(ofSize: 9),
                    .foregroundColor: UIColor.tertiaryLabel
                ]
                let footer = NSAttributedString(string: "Created with Distill", attributes: footerAttrs)
                footer.draw(at: CGPoint(x: margin, y: pageSize.height - margin + 8))
            }
            return tempURL
        } catch {
            return nil
        }
    }
}
